sudo: false
language: clojure
jdk:
 - oraclejdk8
 - openjdk7
install: lein install
script:
 - mkdir /tmp/pseudo-repo
 - cp ci/profiles.clj $HOME/.lein/profiles.clj

 - git clone https://github.com/Prismatic/plumbing.git
 - pushdir plumbing
 - git co plumbing-0.4.4
 - lein datadoc install
 - lein datadoc deploy pseudo-repo
 - popdir

 - pushdir ci
 - lein run datadoc-reader.core
 - popdir

# TODO: Do just the install and deploy without verification on some
#       random, frequently contributed to Clojure project. Tried
#       ClojureScript compiler and Midje, but there appears to be a bug
#       in lib-grimoire. (RM 2015-08-13)
